### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by andreas-bulling** [SiteBeez/wordpress-wp2grav-markdown-exporter#1]
Hi,

I was very happy to find that there is a plugin that finally allows me to get rid of my WordPress installation and move to something light-weight and fast. 
Unfortunately, after installing the plugin and pressing the "Go for it" button, nothing happens. I only see a blank page.

Let me know if I can help with providing version information, debug output etc
I am very much interested in getting this plugin working on my system...

**Comment by cord** [comment]
hi,

There are many possible user adoptions to any wordpress site so hard to say what the issue might be. please try to debug starting with the php error log.

**Comment by andreas-bulling** [comment]
thanks for your reply. Apache's error log shows

PHP Fatal error:  Class 'WP_Screen' not found in /var/www/.../wp-content/plugins/wp2grav/wp2grav.php on line 68, referer: http://.../wp-admin/admin.php?page=wp2grav%2Fwp2grav.php-export

File is there and permissions also seem fine. I also don't see any class in screen.php.

BTW, I am running WP 4.4-alpha

**Comment by cord** [comment]
that must have changed in the new WP versions... would require some development to make it work.

maybe there is a workaround for the WP_Screen class? try to check with google

**Comment by andreas-bulling** [comment]
Fix was easy, change line 48 into
$GLOBALS['current_screen'] = get_current_screen();

**Comment by cord** [comment]
thx, have updated

https://github.com/SiteBeez/wordpress-wp2grav-markdown-exporter/blob/master/wp2grav/wp2grav.php

around line 68 (not 48)
