### ISSUE TITLE
Not working autoinstall and posts export

### ISSUE THREAD

**Issue by giteugen** [SiteBeez/wordpress-wp2grav-markdown-exporter#2]
WP2GRAV_BLOG_MASTER_PAGE_ID' was defined. 
In every folder must be 1 md file. In blogg (BLOG_MASTER_PAGE_ID) - 1 file too. No posts. Other pages seems ok

Could be install just from repository. Zip or "Search" are not.

WordPress 4.4.1

**Comment by cord** [comment]
so far I wasn’t able to understand why the plugin sometimes is not recognised as beeing valid.

for the posts export make sure to configure like described.
